"""
Django settings for bookmanager project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

###  剖析 BASE_DIR, 一层一层解析
# print(__file__)
# /home/caiyzihen/桌面/meiduoshopping/django_base/bookmanager/bookmanager/settings.py

# print(os.path.abspath(__file__))
# /home/caiyzihen/桌面/meiduoshopping/django_base/bookmanager/bookmanager/settings.py

# dirname() 获取文件的目录
# os.path.dirname(os.path.abspath(__file__))
# /home/caiyzihen/桌面/meiduoshopping/django_base/bookmanager/bookmanager

# BASE_DIR
# /home/caiyzihen/桌面/meiduoshopping/django_base/bookmanager
###  所以最终的得到的结果是: BASE_DIR 就是最外层 bookmanager,项目所有的东西都在这个bookmanager文件夹下
###  即项目所有的东西都是以 BASE_DIR 为相对路径


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*@&pj1lee3p0^40oa^i8hv-n@7q*rgq0=z$5d+m-u)6^9@^hd4'

# SECURITY WARNING: don't run with debug turned on in production!
# 调试模式
# 在我们开发的时候，我们需要看到更多的信息，所以要开启debug模式
# 当我们的程序上线之后，就改为False
DEBUG = True

# 允许什么样的形式来访问我们的项目. 默认是 127.0.0.1
ALLOWED_HOSTS = ['*']


# Application definition
#注册/安装子应用
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'book', #方案1
    #'book.apps.BookConfig', #方案2
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bookmanager.urls'

#模板配置相关
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #告知系统，我们的模板文件放在哪里
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bookmanager.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

#设置语言
LANGUAGE_CODE = 'zh-Hans'#'en-us'
#设置时区
TIME_ZONE = 'Asia/Shanghai'#'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
